# run build on every push (expect master branch) and PR
name: development

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and test (development)
    uses: ./.github/workflows/build-and-push.yml
    with:
      push_image: ${{ github.event_name == 'pull_request' }}
      pr_number: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || 0 }}
